site_name: Química 2º Bachillerato
site_url: "https://acarcelenalgaba-bot.github.io/MI_WEB_QUIMICA/"
site_author: Ángel Carcelén Algaba

theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Cambiar a modo claro
  features:
    #- navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - navigation.expand

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: false
      title: "📋 Contenidos"
      toc_depth: 2
  - pymdownx.magiclink


plugins:
  - search
  - kroki
#  - pdf-with-js

extra_javascript:
  - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Inicio: index.md
  - Tema 1 - Estructura atómica: tema1-estructura.md
  - Tema 2 - Enlace químico: tema2-enlace.md
  - Tema 3 - Termoquímica: tema3-termoquimica.md
  - Tema 4 - Cinética química: tema4-cinetica.md
  - Tema 5 - Equilibrio químico: tema5-equilibrio.md
  - Tema 6 - Ácido-base: tema6-acido_base.md
  - Tema 7 - Reacciones redox: tema7-redox.md
  - Tema 8 - Química Orgánica: tema8-organica.md
  - Tema 9 - Polímeros orgánicos: tema9-polimeros.md
