name: Deploy MkDocs con PDFs por Tema

on:
  push:
    branches:
      - main # Asegúrate de que sea la rama correcta (main o master)

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias del sistema gráficos
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libgdk-pixbuf2.0-dev libffi-dev shared-mime-info

      - name: Instalar MkDocs y Plugins
        run: |
          pip install pip --upgrade
          pip install mkdocs-material mkdocs-kroki-plugin mkdocs-pdf-export-plugin

      - name: Compilar y Desplegar en GitHub Pages
        run: |
          mkdocs gh-deploy --force